// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "prisma generate && tsx prisma/seed.ts",
  },
  datasource: {
    url: "postgresql://drift_admin:change_me_strong_password@localhost:5432/drift_masters?schema=public",
  },
});
